version: "3.9"
services:
  api:
    image: korcekj/ms-distance:<tag>
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=<mongodb uri>
      - MONGO_DB=<mongodb name>
      - DM_API_KEY=<distancematrix api key>
      - GC_API_KEY=<geocode api key>